// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Ledger.Infrastructure.Persistence;

#nullable disable

namespace PersonalFinance.Ledger.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260930194719_AddTransactionLegsView")]
    partial class AddTransactionLegsView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PersonalFinance.Infrastructure.Idempotency.InboxConsumedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConsumedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("ledger_inbox_consumed", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("ledger_outbox_messages", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Ledger.Domain.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ledger_accounts", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Ledger.Domain.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrencyCode");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TransactionId");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Ledger.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstallmentReference")
                        .HasColumnType("TEXT")
                        .HasColumnName("InstallmentReferenceId");

                    b.Property<Guid?>("OriginalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SplitReference")
                        .HasColumnType("TEXT")
                        .HasColumnName("SplitReferenceId");

                    b.Property<Guid?>("SubscriptionReference")
                        .HasColumnType("TEXT")
                        .HasColumnName("SubscriptionReferenceId");

                    b.HasKey("Id");

                    b.HasIndex("OriginalTransactionId");

                    b.ToTable("ledger_transactions", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Ledger.Domain.Entry", b =>
                {
                    b.HasOne("PersonalFinance.Ledger.Domain.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Ledger.Domain.Transaction", null)
                        .WithMany("Entries")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinance.Ledger.Domain.Transaction", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
