// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Parties.Infrastructure.Persistence;

#nullable disable

namespace PersonalFinance.Parties.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartiesDbContext))]
    [Migration("20260831030734_InitialPartiesSchema")]
    partial class InitialPartiesSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PersonalFinance.Infrastructure.Idempotency.InboxConsumedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConsumedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("parties_inbox_consumed", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("parties_outbox_messages", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Parties.Domain.ExpenseSplit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AccruedReceivable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AccruedReceivableMinorUnits");

                    b.Property<long>("HolderShare")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HolderShareMinorUnits");

                    b.Property<long>("ReversedReceivable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ReversedReceivableMinorUnits");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Total")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalMinorUnits");

                    b.HasKey("Id");

                    b.ToTable("parties_expense_splits", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Parties.Domain.ExpenseSplitParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExpenseSplitId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Share")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ShareMinorUnits");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseSplitId");

                    b.ToTable("parties_expense_split_participants", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Parties.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceivableAccountId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("parties_parties", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Parties.Domain.ExpenseSplitParticipant", b =>
                {
                    b.HasOne("PersonalFinance.Parties.Domain.ExpenseSplit", null)
                        .WithMany("Participants")
                        .HasForeignKey("ExpenseSplitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PersonalFinance.Parties.Domain.ExpenseSplit", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
