// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Financing.Infrastructure.Persistence;

#nullable disable

namespace PersonalFinance.Financing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinancingDbContext))]
    [Migration("20260830164644_FinancingReadViews")]
    partial class FinancingReadViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PersonalFinance.Financing.Domain.CreditCard", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CarriedCreditBalance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CarriedCreditBalanceMinorUnits");

                    b.Property<int>("CutoffDay")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExpenseAccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LiabilityAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("financing_credit_cards", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Financing.Domain.Installment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AccruedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<int>("CycleMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleYear")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PaymentPlanId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StatementId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentPlanId");

                    b.HasIndex("StatementId");

                    b.ToTable("financing_installments", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Financing.Domain.MonthlyStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountDue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountDueMinorUnits");

                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CycleMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CycleYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PaidOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "CycleYear", "CycleMonth")
                        .IsUnique();

                    b.ToTable("financing_monthly_statements", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Financing.Domain.PaymentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CardId")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<long>("Total")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TotalMinorUnits");

                    b.HasKey("Id");

                    b.ToTable("financing_payment_plans", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Infrastructure.Idempotency.InboxConsumedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConsumedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("financing_inbox_consumed", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("financing_outbox_messages", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Financing.Domain.Installment", b =>
                {
                    b.HasOne("PersonalFinance.Financing.Domain.PaymentPlan", null)
                        .WithMany("Installments")
                        .HasForeignKey("PaymentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PersonalFinance.Financing.Domain.MonthlyStatement", null)
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PersonalFinance.Financing.Domain.PaymentPlan", b =>
                {
                    b.Navigation("Installments");
                });
#pragma warning restore 612, 618
        }
    }
}
