// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalFinance.Subscriptions.Infrastructure.Persistence;

#nullable disable

namespace PersonalFinance.Subscriptions.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SubscriptionsDbContext))]
    [Migration("20260924191856_FlipSubscriptionsToUsd")]
    partial class FlipSubscriptionsToUsd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("PersonalFinance.Infrastructure.Idempotency.InboxConsumedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ConsumedOnUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId", "Consumer");

                    b.ToTable("subscriptions_inbox_consumed", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("subscriptions_outbox_messages", (string)null);
                });

            modelBuilder.Entity("PersonalFinance.Subscriptions.Domain.SubscriptionTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AmountMinorUnits");

                    b.Property<int>("AnchorDay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CurrencyCode");

                    b.Property<Guid>("ExpenseAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FundingAccountId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("LastPaidPeriod")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastPaidTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("NextDueDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("subscriptions_templates", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
